### ISSUE TITLE
Incompatible with Continuity(?)

### ISSUE THREAD

**Issue by PweSol** [MehVahdJukaar/modelfix-multi#12]
crash on startup
```	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at me.pepperbell.continuity.client.util.TextureUtil.<clinit>(TextureUtil.java:10) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.properties.BaseCTMProperties.<clinit>(BaseCTMProperties.java:46) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.ContinuityClient.wrapFactory(ContinuityClient.java:188) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.ContinuityClient.wrapFactory(ContinuityClient.java:192) ~[continuity-2.0.1+1.19.jar:?]
	at me.pepperbell.continuity.client.ContinuityClient.onInitializeClient(ContinuityClient.java:83) ~[continuity-2.0.1+1.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.14.12.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:459) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]```

**Comment by MehVahdJukaar** [comment]
I need full log

**Comment by PweSol** [comment]
[latest.log](https://github.com/MehVahdJukaar/modelfix-multi/files/10356055/latest.log)

**Comment by MehVahdJukaar** [comment]
Hm I'm not sure tbh, no idea why that wouldn't work. So you say it works without continuity?

**Comment by PweSol** [comment]
> Hm I'm not sure tbh, no idea why that wouldn't work. So you say it works without continuity?

Unless it's an incompatibility caused by some specific mod combination, yes.
